### ISSUE TITLE
BUG / investigation - zero actions submitted does not count as a valid turn

### ISSUE THREAD

**Issue by Thaewyn** [DevelopThisOfficial/operation-jungle-knight#56]
Expected: submitting a turn with 0 actions/skills should be a valid turn, cause all status effect / end of turn / monster attack handling.

**Comment by phopps** [comment]
Start by fixing logic in assets/scripts/encounter.js lines 81 (please select fewer than 3 actions) and line 84 (are you sure you don't want to take any actions this turn?)

**Comment by phopps** [comment]
and fix logic in game_controller.js validateTurnSubmission (@JaquelRey)
