### ISSUE TITLE
Seed utilization for 'random' elements

### ISSUE THREAD

**Issue by Thaewyn** [DevelopThisOfficial/operation-jungle-knight#7]
WARNING! Complex task.

We want this game to be "random", but generation from a provided seed should be consistent, no matter who inputs the seed or when. The run 'seed' is provided at the start of the new run (or generated, if none is provided)

- [ ] Hash and save a run seed when a run is started. Create a random seed if one is not provided.

Once the seed has been created, any 'random' elements in the game (which encounters are available, which rewards are provided, etc) are *not* generated from any kind of Math.random function, but are instead pulled from the run's seed string.

- [ ] Create a function that, when provided an input integer (of *where* in the string to pull from) returns an *integer* value of the characters at that position.

**Comment by phopps** [comment]
The branch for issue 7 contains the updated code, but maybe we review and clean up the getPseudoRandom function first before doing any pull request?
